# Generated by Django 5.1.5 on 2025-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akidemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_assignment',
            field=models.ManyToManyField(related_name='assignment_in_courses', to='app_akidemy.assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lesson',
            field=models.ManyToManyField(related_name='lesson_in_courses', to='app_akidemy.lesson'),
        ),
    ]
