# Generated by Django 5.1.5 on 2025-01-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_akidemy', '0002_course_course_assignment_course_course_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_lesson',
        ),
    ]
